#########################################################################################
# DIP SW:
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports  sw_i[0] ]
set_property -dict { PACKAGE_PIN L16 IOSTANDARD LVCMOS33 } [get_ports  sw_i[1] ]
set_property -dict { PACKAGE_PIN M13 IOSTANDARD LVCMOS33 } [get_ports  sw_i[2] ]
set_property -dict { PACKAGE_PIN R15 IOSTANDARD LVCMOS33 } [get_ports  sw_i[3] ]
set_property -dict { PACKAGE_PIN R17 IOSTANDARD LVCMOS33 } [get_ports  sw_i[4] ]
set_property -dict { PACKAGE_PIN T18 IOSTANDARD LVCMOS33 } [get_ports  sw_i[5] ]
set_property -dict { PACKAGE_PIN U18 IOSTANDARD LVCMOS33 } [get_ports  sw_i[6] ]
set_property -dict { PACKAGE_PIN R13 IOSTANDARD LVCMOS33 } [get_ports  sw_i[7] ]
set_property -dict { PACKAGE_PIN T8  IOSTANDARD LVCMOS33 } [get_ports  sw_i[8] ]
set_property -dict { PACKAGE_PIN U8  IOSTANDARD LVCMOS33 } [get_ports  sw_i[9] ]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD LVCMOS33 } [get_ports  sw_i[10]]
set_property -dict { PACKAGE_PIN T13 IOSTANDARD LVCMOS33 } [get_ports  sw_i[11]]
set_property -dict { PACKAGE_PIN H6  IOSTANDARD LVCMOS33 } [get_ports  sw_i[12]]
set_property -dict { PACKAGE_PIN U12 IOSTANDARD LVCMOS33 } [get_ports  sw_i[13]]
set_property -dict { PACKAGE_PIN U11 IOSTANDARD LVCMOS33 } [get_ports  sw_i[14]]
set_property -dict { PACKAGE_PIN V10 IOSTANDARD LVCMOS33 } [get_ports  sw_i[15]]
#########################################################################################
#7-SEG LED:
set_property -dict { PACKAGE_PIN J17 IOSTANDARD LVCMOS33 } [get_ports  an_o[0]]
set_property -dict { PACKAGE_PIN J18 IOSTANDARD LVCMOS33 } [get_ports  an_o[1]]
set_property -dict { PACKAGE_PIN T9  IOSTANDARD LVCMOS33 } [get_ports  an_o[2]]
set_property -dict { PACKAGE_PIN J14 IOSTANDARD LVCMOS33 } [get_ports  an_o[3]]
set_property -dict { PACKAGE_PIN P14 IOSTANDARD LVCMOS33 } [get_ports  an_o[4]]
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS33 } [get_ports  an_o[5]]
set_property -dict { PACKAGE_PIN K2  IOSTANDARD LVCMOS33 } [get_ports  an_o[6]]
set_property -dict { PACKAGE_PIN U13 IOSTANDARD LVCMOS33 } [get_ports  an_o[7]]
set_property -dict { PACKAGE_PIN T10 IOSTANDARD LVCMOS33 } [get_ports  seg_o[7]]
set_property -dict { PACKAGE_PIN R10 IOSTANDARD LVCMOS33 } [get_ports  seg_o[6]]
set_property -dict { PACKAGE_PIN K16 IOSTANDARD LVCMOS33 } [get_ports  seg_o[5]]
set_property -dict { PACKAGE_PIN K13 IOSTANDARD LVCMOS33 } [get_ports  seg_o[4]]
set_property -dict { PACKAGE_PIN P15 IOSTANDARD LVCMOS33 } [get_ports  seg_o[3]]
set_property -dict { PACKAGE_PIN T11 IOSTANDARD LVCMOS33 } [get_ports  seg_o[2]]
set_property -dict { PACKAGE_PIN L18 IOSTANDARD LVCMOS33 } [get_ports  seg_o[1]]
set_property -dict { PACKAGE_PIN H15 IOSTANDARD LVCMOS33 } [get_ports  seg_o[0]]
#########################################################################################